name: Notidy Microsoft 365
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      -name: Send notificatoin to Microsoft 365
      run :|
      curl -H "Content-Type: application/json" -d "{'text': '안녕dokim2'}" https://o365kopo.webhook.office.com/webhookb2/992867cd-ae88-40c2-8a4e-25c38d6c28da@ad21525c-fc0f-4dbc-a403-67ce00add0e4/IncomingWebhook/71ab2019fbd7400cbfb2dc3a1292eb7c/488eb831-b31b-424e-8fec-1a4298ad3af3

